services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: $USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${USER}:${PASSWORD}@db:5432/${NAME}
      - SECRET_KEY=${SECRET_KEY}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
