version: '3.13'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medical_db}
      POSTGRES_USER: ${POSTGRES_USER:-medical_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-medical_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app_network

  web:
    build: .
    command: python -m gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY:-django-insecure-default-secret-key}
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
