# Generated by Django 5.2.4 on 2025-07-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="preparation",
            field=models.TextField(
                blank=True, help_text="Инструкции для пациента перед процедурой", verbose_name="Подготовка к услуге"
            ),
        ),
    ]
