# Generated by Django 5.2.4 on 2025-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_preparation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecategory",
            options={"verbose_name": "Категория исследований", "verbose_name_plural": "Категории исследований"},
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="icon",
            field=models.CharField(
                blank=True,
                default="fa-flask",
                help_text="Font Awesome icon class (например, 'fa-heart')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
