# Generated by Django 5.2.4 on 2025-07-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Основной контент")),
                ("mission", models.TextField(verbose_name="Миссия клиники")),
                (
                    "values",
                    models.TextField(help_text="забота, эффективность, отзывчивость", verbose_name="Наши ценности"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Последнее обновление")),
            ],
            options={
                "verbose_name": 'Страница "О клинике"',
                "verbose_name_plural": 'Страницы "О клинике"',
            },
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL-адрес")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок отображения")),
            ],
            options={
                "verbose_name": "Категория FAQ",
                "verbose_name_plural": "Категории FAQ",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("main_title", models.CharField(max_length=200, verbose_name="Основной заголовок")),
                ("main_description", models.TextField(verbose_name="Основное описание")),
                (
                    "featured_image",
                    models.ImageField(
                        help_text="Рекомендуемый размер: 1200x800 пикселей",
                        upload_to="homepage/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "services_title",
                    models.CharField(default="Наши услуги", max_length=100, verbose_name="Заголовок блока услуг"),
                ),
                (
                    "testimonials_title",
                    models.CharField(
                        default="Отзывы наших пациентов", max_length=100, verbose_name="Заголовок блока отзывов"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активная конфигурация")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Последнее обновление")),
            ],
            options={
                "verbose_name": "Контент главной страницы",
                "verbose_name_plural": "Контент главной страницы",
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "site_name",
                    models.CharField(default="МедДиагностика", max_length=100, verbose_name="Название сайта"),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site_settings/", verbose_name="Логотип")),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site_settings/", verbose_name="Фавикон"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address", models.TextField(verbose_name="Адрес")),
                ("working_hours", models.CharField(max_length=100, verbose_name="Режим работы")),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                ("instagram_url", models.URLField(blank=True, verbose_name="Instagram")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                ("meta_description", models.TextField(blank=True, verbose_name="Мета-описание")),
                ("meta_keywords", models.TextField(blank=True, verbose_name="Мета-ключевые слова")),
            ],
            options={
                "verbose_name": "Настройка сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author", models.CharField(max_length=100, verbose_name="Автор")),
                ("position", models.CharField(blank=True, max_length=100, verbose_name="Должность/статус")),
                ("content", models.TextField(verbose_name="Текст отзыва")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/", verbose_name="Фото автора"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name="Рейтинг"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False, verbose_name="Показывать на главной")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("answer", models.TextField(verbose_name="Ответ")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок отображения")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активный")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.faqcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "question"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("position", models.CharField(max_length=100, verbose_name="Должность")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="team_photos/", verbose_name="Фотография"),
                ),
                ("bio", models.TextField(verbose_name="Биография")),
                ("education", models.TextField(blank=True, verbose_name="Образование")),
                ("experience", models.TextField(blank=True, verbose_name="Опыт работы")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок отображения")),
                ("is_visible", models.BooleanField(default=True, verbose_name="Отображать на сайте")),
                (
                    "about_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="core.aboutpage",
                        verbose_name='Страница "О клинике"',
                    ),
                ),
            ],
            options={
                "verbose_name": "Член команды",
                "verbose_name_plural": "Члены команды",
                "ordering": ["order"],
            },
        ),
    ]
