# Generated by Django 5.2.4 on 2025-07-29 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название отдела")),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="department_images/", verbose_name="Фоновое изображение"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отделы",
            },
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активная страница"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="specialization",
            field=models.CharField(blank=True, max_length=200, verbose_name="Специализация"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="about_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_members",
                to="core.aboutpage",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Биография"),
        ),
        migrations.AddField(
            model_name="teammember",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.department",
                verbose_name="Отдел",
            ),
        ),
    ]
