# Generated by Django 5.2.4 on 2025-07-31 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="education",
        ),
        migrations.RemoveField(
            model_name="doctorprofile",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="department",
            field=models.CharField(default="Общее отделение", max_length=100, verbose_name="Отделение"),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "Мужской"), ("F", "Женский"), ("O", "Другой")], max_length=1
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="doctor_profile", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
