# Generated by Django 5.2.4 on 2025-08-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_doctorprofile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
