# Generated by Django 5.2.4 on 2025-07-27 20:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("appointment_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("results", models.FileField(blank=True, null=True, upload_to="results/")),
                ("doctor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.doctorprofile")),
                (
                    "patient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="services.service")),
            ],
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "working_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        default=list,
                        help_text="Дни недели (0-6, где 0 - понедельник)",
                        size=None,
                    ),
                ),
                ("working_hours", models.JSONField(default=dict, help_text='{"start": "09:00", "end": "18:00"}')),
                ("breaks", models.JSONField(default=list, help_text='[{"start": "13:00", "end": "14:00"}]')),
                (
                    "vacation_dates",
                    models.JSONField(default=list, help_text='[{"start": "2023-08-01", "end": "2023-08-14"}]'),
                ),
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedule", to="users.doctorprofile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание врача",
                "verbose_name_plural": "Расписания врачей",
            },
        ),
    ]
