# Generated by Django 5.2.4 on 2025-07-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="services.service"
            ),
        ),
    ]
